### ISSUE TITLE
allow separate healthcheck config per box

### ISSUE THREAD

**Issue by noerw** [noerw/osem_notify#5]
also restructure config, so we can add separate healthcheck configs per box

```yaml
healthchecks:
  all:
    # override deafult config
  593bcd656ccf3b0011791f5a:
    # set box specific config
```
